networks:
  rede_app:    
    driver: bridge

services:
  app01: &app
    container_name: php-mysql
    build: 
      context: ./container/php/
    hostname: app01  
    networks:
      rede_app:
        aliases:
          - app01
    environment:
      - DB_HOSTNAME=db
      - PORT=9000
    volumes:
      - type: bind
        source: ./backend/app/
        target: /var/www/html/ 
      # descomente alinha abaixo para usar não perder os dados no caso do container ser reiniciado  
#      - ./persistencia/uploads/:/var/www/uploads:Z 
        
  db_my: &data_base
    container_name: mysql8_proc
    build: 
      context: ./container/mysql/
    restart: always
    hostname: db
    networks:
      rede_app:
        aliases:
          - db
    ports:
      - 3308:3306   
        # descomente a linha abaixo para usar não perder os dados no caso do container ser reiniciado
#      - ./persistencia/data_base/:/var/lib/mysql/:Z  
        
  nginx:
    image: nginx
    restart: always
    networks:
      - rede_app
    ports:
      - 9999:80 
    depends_on:
      - app01
    volumes:
      - type: bind
        source: ./container/nginx/nginx.conf
        target: /etc/nginx/nginx.conf 
